FastManga/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('manga.urls', namespace='manga'))
]

manga/urls.py
from django.urls import path
from . import views

app_name = 'manga'
urlpatterns = [
    path('', views.home, name='home'),
    path('login/', views.login, name='login'),
    path('register/', views.register, name='register'),
    path('all-manga/', views.all_manga, name='all_manga'),
    path('manga/<str:manga_code>',views.detail_manga, name='manga'),
    path('chapter/<str:manga_code>/<str:chapter_code>', views.chapter, name='chapter')
]

manga/models.py
from django.db import models
from django.utils import timezone

# Create your models here.
class User(models.Model):
    username = models.CharField(max_length=200)
    password = models.CharField(max_length=200)

    def __str__(self):
        return self.username

class Author(models.Model):
    code = models.CharField(max_length=20)
    name = models.CharField(max_length=20)

    def __str__(self):
        return self.name

class Genre(models.Model):
    name = models.CharField(max_length=20)

    def __str__(self):
        return self.name

class Manga(models.Model):
    code = models.CharField(max_length=30, unique=True, null=True, default='0000')
    name = models.CharField(max_length=100)
    last_updated = models.DateTimeField(default=timezone.now)
    author = models.ManyToManyField(Author)
    ongoing = models.BooleanField(default=True)
    genre = models.ManyToManyField(Genre)
    views = models.IntegerField(default=0)
    total_star = models.IntegerField(default=0)
    total_votes = models.IntegerField(default=0)
    thumbnail_url = models.URLField(max_length=200, default=None)
    description = models.TextField(default=None)

    def __str__(self):
        return self.name

class Chapter(models.Model):
    name = models.CharField(max_length=30)
    num_page = models.IntegerField(default=0)
    manga = models.ForeignKey(Manga, on_delete=models.CASCADE)
    cdn_url = models.URLField(max_length=200, default=None)
    code = models.CharField(max_length=30, default=None, unique=False, null=True)
    last_updated = models.DateTimeField(default=timezone.now)
    views = models.IntegerField(default=0)
    def __str__(self):
        return self.name + ' of ' + self.manga.name
    

manga/views.py
from django.shortcuts import render
from django.http import HttpResponse, Http404, HttpResponseRedirect
from django.template import loader
from django.urls import reverse
import subprocess
import os
from django.utils.datastructures import MultiValueDictKeyError
from .models import Manga, Chapter, User, Author
# from . models import User, Job
# import requests
import json
from .utils import top3recentchapter, updated_time_templates
# templates_path = "F:\\Projects\\FastManga\\manga\\templates"
def home(request):
    template = loader.get_template('manga/home.html')
    # return render(request, templates_path + '\\manga\\home.html')
    manga_query_set = Manga.objects.order_by('-last_updated')[:12]
    # for item in mangas:
    mangas = []
    #lấy ra mangas + top 3 chap gần nhất + thời gian từng chap
    for item in manga_query_set:
        top3_recent_chap_list = [{'time_text' : updated_time_templates(chap), 'main' : chap} for chap in top3recentchapter(item)]
        mangas.append({'main' : item, 'top3_recent_chap_list' : top3_recent_chap_list})

    top_10_popular_manga_query_set = Manga.objects.order_by('-views')[:10]
    # top_8_popular_manga_most_recent_chapter_name = [item.chapter_set.order_by('-last_updated')[0].name for item in top_8_popular_manga]

    #lấy ra top 10 popular manga + tên chap gần nhất
    top_10_popular_mangas = []
    for item in top_10_popular_manga_query_set:
        most_recent_chapter_name = item.chapter_set.order_by('-last_updated')[0].name
        top_10_popular_mangas.append({'main' : item, 'most_recent_chapter_name' : most_recent_chapter_name})

    context = {
        'mangas' : mangas,
        'top_10_popular_mangas' : top_10_popular_mangas,
    }

    print(top_10_popular_mangas)
    return HttpResponse(template.render(context, request))

def login(request):
    return HttpResponse("day la trang dang nhap")

def register(request):
    return HttpResponse("day la trang dang ky")

def all_manga(request):
    return HttpResponse("day la trang view truyen")

def detail_manga(request, manga_code):
    top_10_popular_manga_query_set = Manga.objects.order_by('-views')[:10]
    top_10_popular_mangas = []
    for item in top_10_popular_manga_query_set:
        most_recent_chapter_name = item.chapter_set.order_by('-last_updated')[0].name
        top_10_popular_mangas.append({'main' : item, 'most_recent_chapter_name' : most_recent_chapter_name})

    manga = Manga.objects.get(code=manga_code)
    genres = manga.genre.all()
    authors = manga.author.all()
    chapters_query_set = manga.chapter_set.all()
    # rating = 
    template = loader.get_template('manga/manga.html')
    chapters_updated_text = [updated_time_templates(item) for item in chapters_query_set]
    chapters = []
    for i in range(len(chapters_query_set)):
        chapters.append({'main' : chapters_query_set[i], 'updated_text' : chapters_updated_text[i] })
    context = {
        'manga' : manga,
        'genres' : genres,
        'chapters' : chapters,
        'first_author': authors[0],
        'first_genre' : genres[0],
        'top_10_popular_mangas' : top_10_popular_mangas
    }
    if len(authors) > 1:
        context['remain_authors'] = authors[1:]

    if len(genres) > 1:
        context['remain_genres'] = genres[1:]

    manga.views += 1
    manga.save()

    print(context)
    return HttpResponse(template.render(context, request))
    
def chapter(request, manga_code, chapter_code):
    # return HttpResponse("day la trang chapter %s cua %s" % (chapter_code, manga_code))
    manga = Manga.objects.get(code=manga_code) 
    chapter = Chapter.objects.get(manga=manga.id, code=chapter_code)
    num_pages = range(chapter.num_page)
    context = {'chapter' : chapter, 'manga' : manga, 'num_pages' : num_pages}
    template = loader.get_template('manga/chapter.html')
    return HttpResponse(template.render(context, request))

manga/templates/manga/chapter.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>FaManga - Đọc truyện tranh online</title>
        {% load static %}
        <link rel="icon" type="image/png" href="{% static 'img/logo.png' %}">
        <link rel="stylesheet" href="{% static 'css/c-style.css' %}" />
        <link rel="stylesheet" href="{% static 'css/owl.theme.css' %}" />
        <link rel="stylesheet" href="{% static 'css/owl.carousel.css' %}" />
        <link rel="stylesheet" href="{% static 'css/tooltip.css' %}" />
        <link rel="stylesheet" href="{% static 'css/c-style-search.css' %}" />
        <link rel="stylesheet" href="{% static 'css/c-style-chapter.css' %}" />
        <link href='https://fonts.googleapis.com/css?family=Noto+Sans:400,400italic,700,700italic&subset=latin,vietnamese' rel='stylesheet' />
        <script type="text/javascript" src="{% static 'js/jquery-1.9.1.min.js' %}"></script>
        <script type="text/javascript" src="{% static 'js/owl.carousel.js' %}"></script>
        <script type="text/javascript" src="{% static 'js/cookie.js' %}"></script>
        <script type="text/javascript" src="{% static 'js/custom.js' %}"></script>
        <script type="text/javascript" src="{% static 'js/tooltip.js' %}"></script>
        <script type="text/javascript" src="{% static 'js/fsearch.js' %}"></script>
        <script type="text/javascript" src="{% static 'js/changes-mode-chapter.js' %}"></script>
        <script type="text/javascript" src="{% static 'js/custom-chapter.js' %}"></script>
        <script type="text/javascript" src="{% static 'js/lazysizes.min.js' %}"></script>
        <!-- <link rel="stylesheet" href="https://manganelo.com/themes/starrate/css/style.css" />
        <script type="text/javascript" src="https://manganelo.com/themes/starrate/js/starwarsjs.js"></script> -->
    </head>
<body>
    <div class="container">
        <div class="panel-logo-chapter">
            <a href="{% url 'manga:home' %}" title="Read Manga Online">
            <img src="https://manganelo.com/themes/hm/images/logo-chap.png" alt="Read Manga Online - manganelo" title="Read Manga Online - manganelo">
            </a>
        </div>
        <div class="panel-breadcrumb">
            <a class="a-h" href="{% url 'manga:home' %}" title="Read Manga Online">Read Manga Online</a>
            <span>»</span>
            <a class="a-h" href="{% url 'manga:manga' manga.code %}" title="Zero Point Idol">{{manga.name}}</a>
            <span>»</span>
            <a class="a-h" href="{% url 'manga:chapter' manga.code chapter.code %}" title="Chapter 1: First encounter">{{chapter.name}}</a>
        </div>
        <div class="panel-navigation">
            <select class="navi-change-chapter">
                <option data-c="1" selected="">{{chapter.name}}</option>
            </select>
            <div class="navi-change-chapter-btn">
                <a rel="nofollow" class="navi-change-chapter-btn-next a-h" href="#">NEXT CHAPTER<i></i>
                </a>
            </div> 
            
        </div>
    </div>
    <div class="container-chapter-reader">
        {% for num in num_pages %}
        <img src="/static/manga/{{manga.code}}/{{chapter.code}}/{{num}}.jpg" alt="{{manga.name}} {{chapter.name}} page num - Famanga" title="{{manga.name}} {{chapter.name}} page num - Famanga" style="margin-top: 5px;">
        {% endfor %}
    </div>
</body>
</html>

manga/templates/manga/header.html
<div class="container container-header">
    <div class="logo">
        <a href="/" title="Manga Online">
            {% load static %}
            <img src="{% static 'img/logo_small.png' %}" alt="Manga Online" title="Manga Online">
        </a>
    </div>
    <div class="container-header-top">
        <div class="box-search">
            <form name="frmsearch">
                <input id="search-story" autocomplete="off" placeholder="Tìm kiếm" class="search-story searchi">
                    <div id="SearchResult">
                        <ul></ul>
                            <div id="search-footer" class="searchf">
                        </div>
                    </div>
                <input style="display: none;">
            </form>
        </div>
        <div class="box-user-options">
            <a rel="nofollow" href="{% url 'manga:login' %}" class="user-login">Đăng nhập</a>
            <a rel="nofollow" href="{% url 'manga:register' %}" class="user-register">Đăng ký</a>
            <!-- <i class="mode-changer"></i> -->
        </div>
    </div>
    <a class="header-mobile-menu">MENU</a>
    <div class="header-menu">
        <a class="a-h" href="{% url 'manga:home' %}" title="Manga Online">MANGA ONLINE</a>
        <a class="a-h" href="{% url 'manga:all_manga' %}" title="LATEST MANGA">LATEST MANGA</a>
        <a class="a-h" href="{% url 'manga:all_manga' %}" title="HOT MANGA">HOT MANGA</a>
        <a class="a-h" href="{% url 'manga:all_manga' %}" title="NEWEST MANGA">NEWEST MANGA</a>
    </div>
</div>

manga/templates/manga/main-left-manga.html
<div class="container-main-left">
    <div style="width: 100%;overflow: hidden;text-align: center;float: left;">
    <div style="max-width: 728px;max-height: 90px;overflow: hidden;margin: 0px auto;">
    <iframe src="/ads/adtrue_728x90_desktop.html" scrolling="no" frameborder="0" style="width: 728px;height: 90px;"></iframe>
    </div>
    </div>
    <script type="application/javascript">
        $votepointstar = '4';
        $defaultpointrating = '4.26';
        $postid = '26021';
        $ddrate = 'https://manganelo.com/story_vote';
        $ddbookmark = 'https://manganelo.com/setbookmark';
        $lg = false;
    </script>
    <script>
        isfollowed = false;
        jQuery(document).ready(function($) {
            $(".story-bookmark").click(function() {
                if($lg == false) {
                    show_notication_popup('You need to log in to use this function.');
                    return;
                }
            });
        });
    </script>
    <div class="panel-breadcrumb">
    <a class="a-h" href="{% url 'manga:home' %}" title="Read Manga Online">Read Manga Online</a>
    <span>»</span>
    <a class="a-h" href="{% url 'manga:manga' manga.code %}" title="{{ manga.name }}">
    {{ manga.name }} </a>
    </div>
    <div class="panel-story-info">
    <div class="story-info-left">
    <span class="info-image">
    <img class="img-loading" src="{{ manga.thumbnail_url }}" alt="{{ manga.name }}" title="{{ manga.name }}" onerror="javascript:this.src='https://manganelo.com/themes/hm/images/404_not_found.png';">
    </span>
    <span class="style-btn btn-chapterlist">READ CHAPTER LIST</span>
    </div>
    <div class="story-info-right">
    <h1>{{ manga.name }}</h1>
    <table class="variations-tableInfo">
    <tbody>
    <tr>
    <td class="table-label"><i class="info-author"></i>Tác giả :</td>
        <td class="table-value">
            <a rel="nofollow" class="a-h" href="#">{{first_author.name}}</a> 
            {% if remain_authors %}
                {% for item in remain_authors %}
                - <a rel="nofollow" class="a-h" href="#">{{ item.name }}</a> 
                {% endfor %}
            {% endif %}
        </td>
    </tr>
    <tr>
    <td class="table-label"><i class="info-status"></i>Trạng thái :</td>                
    <td class="table-value">
    {% if manga.ongoing %}
        Còn tiếp
    {% else %}
        Đủ bộ
    {% endif %}
    </td>
    </tr>
    <tr>
    <td class="table-label"><i class="info-genres"></i>Thể loại :</td>
    <td class="table-value">
    <a class="a-h" href="#">{{ first_genre.name }}</a> 
    {% if remain_genres %}
        {% for item in remain_genres %}
            - <a rel="nofollow" class="a-h" href="#">{{ item.name }}</a> 
        {% endfor %}
    {% endif %}
    </td>
    </tr>
    </tbody>
    </table>
    <div class="story-info-right-extent">
    <p><span class="stre-label"><i class="info-time"></i>Cập nhật mới nhất :</span><span class="stre-value">Jan 02,2021 - 10:50 AM</span></p>
    <p><span class="stre-label"><i class="info-view"></i>Lượt xem :</span><span class="stre-value">2,725,024</span></p>
    <p>
    <span class="stre-label"><i class="info-rate"></i>Đánh giá :</span>
    <span class="stre-value">
    <em class="rate_row" id="rate_row">
        <span class="rate_star checked" data-value="1"></span>
        <span class="rate_star checked" data-value="2"></span>
        <span class="rate_star checked" data-value="3"></span>
        <span class="rate_star checked" data-value="4"></span>
        <span class="rate_star" data-value="5"></span>
        <input type="hidden" class="get_rate" value="4" default-stars="4"></em>
    <em class="rate_row_result"></em>
    </span>
    </p>
    <p>
    <em id="rate_row_cmd">
    <em xmlns:v="http://rdf.data-vocabulary.org/#" typeof="v:Review-aggregate">
    <em property="v:itemreviewed">MangaNelo.com</em>
    <em rel="v:rating">
    <em typeof="v:Rating">rate :
    <em property="v:average">4.26</em>/
    <em property="v:best">5</em>
    </em>
    </em> - <em property="v:votes">285</em> votes
    </em>
    </em>
    </p>
    <!-- <p class="info-bookmark">
    <img class="story-bookmark" src="https://manganelo.com/themes/hm/images/bookmark.png">
    </p>
    <p class="noti-bookmark"></p>
    <p class="fb-save fb_iframe_widget" data-uri="https://manganelo.com/manga/zero_point_idol" data-size="small" id="savefilmfb" fb-xfbml-state="rendered" fb-iframe-plugin-query="app_id=190712595201460&amp;container_width=606&amp;locale=en_US&amp;sdk=joey&amp;size=small&amp;uri=https%3A%2F%2Fmanganelo.com%2Fmanga%2Fzero_point_idol"><span style="vertical-align: bottom; width: 132px; height: 20px;"><iframe name="f2f6e826eabdcbc" width="1000px" height="1000px" data-testid="fb:save Facebook Social Plugin" title="fb:save Facebook Social Plugin" frameborder="0" allowtransparency="true" allowfullscreen="true" scrolling="no" allow="encrypted-media" src="https://www.facebook.com/plugins/save.php?app_id=190712595201460&amp;channel=https%3A%2F%2Fstaticxx.facebook.com%2Fx%2Fconnect%2Fxd_arbiter%2F%3Fversion%3D46%23cb%3Dfc420073b5c8a%26domain%3Dmanganelo.com%26origin%3Dhttps%253A%252F%252Fmanganelo.com%252Ff21e19eb79c0d44%26relation%3Dparent.parent&amp;container_width=606&amp;locale=en_US&amp;sdk=joey&amp;size=small&amp;uri=https%3A%2F%2Fmanganelo.com%2Fmanga%2Fzero_point_idol" style="border: none; visibility: visible; width: 132px; height: 20px;" class=""></iframe></span></p>
    <div class="fb-like fb_iframe_widget" data-href="https://manganelo.com/manga/zero_point_idol" data-layout="button_count" data-action="like" data-show-faces="false" data-share="true" fb-xfbml-state="rendered" fb-iframe-plugin-query="action=like&amp;app_id=190712595201460&amp;container_width=606&amp;href=https%3A%2F%2Fmanganelo.com%2Fmanga%2Fzero_point_idol&amp;layout=button_count&amp;locale=en_US&amp;sdk=joey&amp;share=true&amp;show_faces=false"><span style="vertical-align: bottom; width: 150px; height: 28px;"><iframe name="ff3271e659c8c4" width="1000px" height="1000px" data-testid="fb:like Facebook Social Plugin" title="fb:like Facebook Social Plugin" frameborder="0" allowtransparency="true" allowfullscreen="true" scrolling="no" allow="encrypted-media" src="https://www.facebook.com/plugins/like.php?action=like&amp;app_id=190712595201460&amp;channel=https%3A%2F%2Fstaticxx.facebook.com%2Fx%2Fconnect%2Fxd_arbiter%2F%3Fversion%3D46%23cb%3Df137009e0b934c%26domain%3Dmanganelo.com%26origin%3Dhttps%253A%252F%252Fmanganelo.com%252Ff21e19eb79c0d44%26relation%3Dparent.parent&amp;container_width=606&amp;href=https%3A%2F%2Fmanganelo.com%2Fmanga%2Fzero_point_idol&amp;layout=button_count&amp;locale=en_US&amp;sdk=joey&amp;share=true&amp;show_faces=false" style="border: none; visibility: visible; width: 150px; height: 28px;" class=""></iframe></span></div> -->
    </div>
    </div>
    <div class="panel-story-info-description" id="panel-story-info-description" style="max-height: none;">
        <h3>Description :</h3>
        {{manga.description}} 
    </div>
    <div id="panel-description-linear">
    <i id="pn-description-linear-gradient" style="display: none;"></i>
    </div>
    <span style="display: none;" id="panel-story-info-description-show-more" class="a-h">SHOW MORE ⇩</span>
    <span style="display: initial;" id="panel-story-info-description-show-less" class="a-h">SHOW LESS ⇧</span>
    </div>
    <script>
        link_chapter_null = 'https://manganelo.com/chapter/zero_point_idol/chapter_';
    </script>
    <div class="panel-story-chapter-list">
    <p class="row-title-chapter" style="width: calc(100% - 19px);">
    <span class="row-title-chapter-name">Chapter name</span>
    <span class="row-title-chapter-view">View</span>
    <span class="row-title-chapter-time">Uploaded</span>
    </p>
    <ul class="row-content-chapter">
    {% for chapter in chapters %}
        <li class="a-h">
        <a rel="nofollow" class="chapter-name text-nowrap" href="{% url 'manga:chapter' manga.code chapter.main.code %}" title="{{ manga.name }} {{chapter.main.name}}">{{ chapter.main.name }}</a>
        <span class="chapter-view text-nowrap">{{chapter.main.views}}</span>
        <span class="chapter-time text-nowrap" title="Jan 02,2021 10:01">{{chapter.updated_text}}</span>
        </li>               
    {% endfor %}
    </ul>
    </div>
    <!-- <div class="panel-story-comment panel-fb-comment a-h">
    <p class="fb-comment-title fb-comment-title-hidden"><span>Facebook Comments</span><i></i></p>
    <div class="fb-comments-content" id="aHR0cDovL21hbmdhbmVsby5jb20vbWFuZ2EvemVyb19wb2ludF9pZG9s"></div>
    </div>
    <script type="text/javascript" src="https://manganelo.com/themes/hm/js/custom-story.js?v=1.1.4"></script> </div> -->
</div>

manga/templates/manga/manga.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{manga.name}} - FaManga - Đọc truyện tranh online</title>
    {% load static %}
    <link rel="icon" type="image/png" href="{% static 'img/logo.png' %}">
    <link rel="stylesheet" href="{% static 'css/c-style.css' %}" />
    <link rel="stylesheet" href="{% static 'css/owl.theme.css' %}" />
    <link rel="stylesheet" href="{% static 'css/owl.carousel.css' %}" />
    <link rel="stylesheet" href="{% static 'css/tooltip.css' %}" />
    <link rel="stylesheet" href="{% static 'css/c-style-search.css' %}" />
    <link href='https://fonts.googleapis.com/css?family=Noto+Sans:400,400italic,700,700italic&subset=latin,vietnamese' rel='stylesheet' />
    <script type="text/javascript" src="{% static 'js/jquery-1.9.1.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/owl.carousel.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/cookie.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/custom.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/tooltip.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/fsearch.js' %}"></script>
    <!-- <link rel="stylesheet" href="https://manganelo.com/themes/starrate/css/style.css" />
    <script type="text/javascript" src="https://manganelo.com/themes/starrate/js/starwarsjs.js"></script> -->
</head>
<body>
    <div class="body-site">
        {% include "header.html" %}
           
        <div class="container container-main">
            {% include "main-left-manga.html" %}
            {% include "main-right.html" %}
        </div>
    </div>
</body>
</html>